### ISSUE TITLE
Using Docker, unable to login using authentication

### ISSUE THREAD

**Issue by IoSonoPiero** [misterunknown/ifm#198]
Hello people, after 1,5 hours of failed attempts, I gave up! :)
So,
I created a docker-compose.yml file with:
```
services:
  ifm:
    image: ifm:latest
    container_name: ifm
    restart: always
    environment:
      - IFM_TIMEZONE=Europe/Rome
      - IFM_DOCKER_UID=1000
      - IFM_DOCKER_GID=1000
      - IFM_AUTH=1
      - IFM_AUTH_SOURCE="inline;admin:$2y$05$Qqharvi17lAdgPHzkustBOVst1nFJyDRK9YM58xoEcRe6dTA2R0n."
    ports:
      - "8080:80"
    volumes:
      - /mnt/NAS:/var/www
```
To generate the hash from password "password", I used:
```htpasswd -nbB admin password```

Reading the documentation, I see [here](https://github.com/misterunknown/ifm/wiki/Authentication) that I have to specify one of these three values:
-     inline
-     file
-     ldap
I choose inline, even if in the Docker section I see:
```docker run --rm -i -p "8080:80" -v /var/www:/var/www \
  -e IFM_AUTH=1 -e IFM_AUTH \
  -e IFM_AUTH_SOURCE="admin:$2y$05$LPdE7u/5da/TCE8ZhqQ1o.acuV50HqB3OrHhNwxbXYeWmmZKdQxrC" \
  ifm
```
where I think there is an error too, because IFM_AUTH is specified two times.

When I start the container, and try to login with:
username: admin
password: password
I always get the magical ```Authentication failed: Wrong credentials``` error.
In the docker-compose.yml file I tried 
```      - IFM_AUTH_SOURCE="admin:$2y$05$Qqharvi17lAdgPHzkustBOVst1nFJyDRK9YM58xoEcRe6dTA2R0n."```
too, without the inline, but with the same result.
What am I doing wrong?
